### ISSUE TITLE
The proof of the fact 3.1 in Appendix

### ISSUE THREAD

**Issue by Supgb** [Chrisa142857/neuro_detour#2]
Hi, Thank you for sharing this attractive work!

However, I cannot get the point of the Fact 3-1 in Section 3. Also, its proof in the appendix is hard to understand, such as Eq.(10).

Could you help me with a simpler explanation?

**Comment by Chrisa142857** [comment]
Hi, thanks for your interest. Fact 3-1 is pointing out the path representation feature of our model. Since different paths have their corresponding features to be weighted sum in our model, the collection of simple paths that can be assigned with a feature is denoted by $P^H_i$ in Fact 3-1. 

In our proof, $P^H_i$ is deduced as Eq.10 given Eq.9 and 8 describing that the walk by adjacency matrix multiplication will revisit the same node every other hop. 

Best,
Ziquan
